local_backend: true

# Use DecapBridge auth (required)
backend:
  name: git-gateway
  repo: lifewithshortarms/lifewithshortarms.github.io
  branch: main
  identity_url: https://auth.decapbridge.com/sites/dbc5f218-9676-4597-9543-33edff00d8da
  gateway_url: https://gateway.decapbridge.com

  # Quickly see who did what (optional)
  commit_messages:
    create: Create {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    update: Update {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    delete: Delete {{collection}} “{{slug}}” - {{author-name}} <{{author-login}}> via DecapBridge
    uploadMedia: Upload “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    deleteMedia: Delete “{{path}}” - {{author-name}} <{{author-login}}> via DecapBridge
    openAuthoring: Message {{message}} - {{author-name}} <{{author-login}}> via DecapBridge

# Better Decap + Bridge logo (optional)
logo_url: https://decapbridge.com/decapcms-with-bridge.svg

# Add site links in DecapCMS (optional)
site_url: https://lifewithshortarms.github.io

media_folder: "/public/media" # Media files will be stored in the repo under this path
public_folder: "/public" # The src attribute for uploaded media will begin with this path

collections:

  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title (required)", name: "title", widget: "string" }
      - { label: "Description (required)", name: "description", widget: "markdown" }
      - { label: "File", name: "file", widget: "file", required: false, media_library: { config: { multiple: true } } }
      - { label: "Body (required)", name: "body", widget: "markdown" }

  - name: "media"
    label: "Media"
    folder: "content/media"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title (required)", name: "title", widget: "string" }
      - { label: "Description (required)", name: "description", widget: "markdown" }
      - { label: "File", name: "file", widget: "file", required: false, media_library: { config: { multiple: true } } }
      - { label: "URL / Link (required)", name: "url", widget: "string" }
      - { label: "Featured Image", name: "image", widget: "image", required: false, media_library: { config: { multiple: false } } }
      - { label: "Featured Image Description", name: "image_description", widget: "string" }
